# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: exam_test

  adminer:
    image: adminer
    ports:
      - 9090:8080

  app:
    build: .
    environment: 
      JAVA_OPTIONS: "-DMYSQL_USER=root -DMYSQL_URL=db:3306/exam_test -DMYSQL_PASSWORD=example"
    ports:
      - 8080:8080